const questions = [
  // STATE / Interference (50 questions)
  { text: "Total workplace democracy is desirable.", axis: "interference", direction: 1 },
  { text: "A decentralised economy is ideal.", axis: "interference", direction: 1 },
  { text: "The tripartite co-operation between State, Employee and Employer is essential for the economy.", axis: "interference", direction: -1 },
  { text: "The DPRK has a foreign policy that we should emulate.", axis: "interference", direction: -1 },
  { text: "All within the state, nothing outside the state, nothing against the state.", axis: "interference", direction: -1 },
  { text: "The state must be totalitarian in nature.", axis: "interference", direction: -1 },
  { text: "Any variant of anarchism will never work.", axis: "interference", direction: -1 },
  { text: "It is very important to maintain and enforce law and order.", axis: "interference", direction: -1 },
  { text: "State surveilence is an essential tool.", axis: "interference", direction: -1 },

  // OWNERSHIP (50 questions)
  { text: "All material wealth should be held in collective.", axis: "ownership", direction: -1 },
  { text: "The right to property is fundemental.", axis: "ownership", direction: 1 },
  { text: "There is no wrong in permitting small business.", axis: "ownership", direction: 1 },
  { text: "Private ownership promotes responsibility, innovation, and virtue in society.", axis: "ownership", direction: 1 },
  { text: "The state should actively intervene to break up large concentrations of private property and redistribute it more broadly.", axis: "ownership", direction: 1 },
  { text: "Market competition is essential to a healthy state.", axis: "ownership", direction: 1 },
  { text: "The workers need to own the means of production.", axis: "ownership", direction: -1 },
  { text: "Tax land, not labor.", axis: "ownership", direction: 1 },
  { text: "Corporatism is just state-capitalism.", axis: "ownership", direction: -1 },
  { text: "Red Fascism is a cool concept.", axis: "ownership", direction: -1 },

  // TRADITION (50 questions)
  { text: "Empire-building and conquering can be virtuous.", axis: "tradition", direction: 1 },
  { text: "War imposes the stamp of nobility upon the peoples who have the courage to make it.", axis: "tradition", direction: -1 },
  { text: "Races are arbitrary constructs.", axis: "tradition", direction: -1 },
  { text: "The monarchy is an important aspect of our culture that must be preserved.", axis: "tradition", direction: 1 },
  { text: "We must revolt against modernity, not just the modern world as it is but modernity itself.", axis: "tradition", direction: 1 },
  { text: "The distant past had a superior method of societal organisation.", axis: "tradition", direction: 1 },
  { text: "The Futurist art movement is virtuous.", axis: "tradition", direction: -1 },
  { text: "We must erase all traces of the past civilisations.", axis: "tradition", direction: -1 },
  { text: "In the future, we should improve our biology with technology.", axis: "tradition", direction: -1 },
  { text: "Damage to the environment is acceptable if it furthers the nation's goals.", axis: "tradition", direction: -1 },
  { text: "The Industrial Revolution was a neccessary development in history.", axis: "tradition", direction: -1 },
  { text: "Environmentalism is internationalist.", axis: "tradition", direction: 1 },
  { text: "A better world will come from automation, science, and technology.", axis: "tradition", direction: -1 },
  { text: "We must protect nature, even if that means lowering our quality of life.", axis: "tradition", direction: 1 },
  { text: "Agrarian and rural living is superior to urbanism.", axis: "tradition", direction: 1 },
  { text: "We should be skeptical of new technologies.", axis: "tradition", direction: 1 },
  { text: "Agriculture didn't just domesticate the pig and the cow, but man himself.", axis: "tradition", direction: 1 },
  { text: "We should return to a primitive lifestyle.", axis: "tradition", direction: 1 },
  { text: "A violent future must be embraced.", axis: "tradition", direction: -1 },
  
  // FAITH (50 questions)
  { text: "There is such a thing as inalienable rights.", axis: "faith", direction: 1 },
  { text: "All religions should be treated equally before the state.", axis: "faith", direction: -1 },
  { text: "Religious values should not influence governance.", axis: "faith", direction: -1 },
  { text: "Religion is a psychic disease of the brain.", axis: "faith", direction: -1 },
  { text: "Religious morality only hinders progress.", axis: "faith", direction: -1 },
  { text: "The seperation between church and state is paramount.", axis: "faith", direction: -1 },
  { text: "There are moral rules that should never be broken.", axis: "faith", direction: 1 },
  { text: "Schools should induce spiritual education.", axis: "faith", direction: 1 },
  { text: "The nation must be united under one religion.", axis: "faith", direction: 1 },
  { text: "My religion must be respected.", axis: "faith", direction: 1 },
  { text: "Atheism is deplorable.", axis: "faith", direction: 1 },
  { text: "Jesus Christ is God.", axis: "faith", direction: 1 },
  { text: "Paganism is barbaric.", axis: "faith", direction: 1 },
  { text: "I believe in the supernatural.", axis: "faith", direction: 1 },
];
