const questions = [
  // ==================== INTERFERENCE (State control over economy) ====================
  { text: "Workplaces should be run directly by the people who work in them.", axis: "interference", direction: 1 },
  { text: "Top national leadership should have final control over all economic goals.", axis: "interference", direction: -1 },
  { text: "The economy should be managed through tripartite cooperation between the state, workers, and employers.", axis: "interference", direction: -1 },
  { text: "Economic self-sufficiency and autarky are more important than global trade.", axis: "interference", direction: -1 },
  { text: "The state should act as the final arbiter in disputes between different economic groups.", axis: "interference", direction: -1 },
  { text: "Trades, professions and regions should be largely free to develop in their own organic way.", axis: "interference", direction: 1 },
  { text: "Local economies function best with minimal interference from the capital.", axis: "interference", direction: 1 },
  { text: "National economic plans should guide the overall direction of the economy.", axis: "interference", direction: -1 },
  { text: "Strong central oversight is necessary to maintain economic stability.", axis: "interference", direction: -1 },
  { text: "People in each trade or guild should choose their own leaders.", axis: "interference", direction: 1 },
  { text: "Only the government can fairly regulate large institutions and corporations.", axis: "interference", direction: -1 },
  { text: "Economic decisions should be made primarily by those directly involved in production.", axis: "interference", direction: 1 },
  { text: "Local groups and communities should adapt their economies to their own specific needs.", axis: "interference", direction: 1 },
  { text: "The state's main role is to serve society rather than direct and control it.", axis: "interference", direction: 1 },
  { text: "Small businesses, family workshops and farms should be the backbone of the economy.", axis: "interference", direction: 1 },
  { text: "Large bureaucratic state systems are usually inefficient and should be minimized.", axis: "interference", direction: 1 },
  { text: "Most day-to-day economic decisions should be handled by local groups and guilds.", axis: "interference", direction: 1 },
  { text: "Some regions and trades deserve significant economic autonomy.", axis: "interference", direction: 1 },
  { text: "A decentralized economy generally works better than a highly centralized one.", axis: "interference", direction: 1 },
  { text: "Social support should come primarily from communities and voluntary associations rather than the state.", axis: "interference", direction: 1 },
  { text: "Wages and working conditions should be guided or set by national rules.", axis: "interference", direction: -1 },
  { text: "Economic life should revolve around strong local communities and organic structures.", axis: "interference", direction: 1 },
  { text: "Trades and professions should be free to organize themselves without heavy state interference.", axis: "interference", direction: 1 },
  { text: "Worker syndicates and guilds require state supervision to function properly.", axis: "interference", direction: -1 },
  { text: "National goals must always take priority over local or regional interests.", axis: "interference", direction: -1 },

  // ==================== OWNERSHIP ====================
  { text: "All material wealth should ultimately be held collectively.", axis: "ownership", direction: -1 },
  { text: "The right to private property is fundamental to a healthy society.", axis: "ownership", direction: 1 },
  { text: "There is nothing wrong with permitting small businesses and family enterprises.", axis: "ownership", direction: 1 },
  { text: "Private ownership encourages responsibility, innovation and virtue.", axis: "ownership", direction: 1 },
  { text: "The state should break up large concentrations of private property and redistribute them.", axis: "ownership", direction: -1 },
  { text: "Market competition is essential for a dynamic and healthy economy.", axis: "ownership", direction: 1 },
  { text: "The workers must own the means of production.", axis: "ownership", direction: -1 },
  { text: "Taxing land is preferable to taxing labour.", axis: "ownership", direction: 1 },
  { text: "Communism is a better system than capitalism.", axis: "ownership", direction: -1 },
  { text: "Everyone should have the realistic opportunity to own their own home.", axis: "ownership", direction: 1 },
  { text: "Essential industries like water, healthcare and housing should not be left solely to private markets.", axis: "ownership", direction: -1 },
  { text: "Key infrastructure such as roads, power and communications should be publicly owned.", axis: "ownership", direction: -1 },
  { text: "Large plots of land and property should remain in private hands.", axis: "ownership", direction: 1 },
  { text: "Heavy regulations on private business are usually harmful to the economy.", axis: "ownership", direction: 1 },
  { text: "The employer is naturally in conflict with the worker.", axis: "ownership", direction: -1 },
  { text: "The bourgeoisie can be integrated and re-socialized under a new system.", axis: "ownership", direction: 1 },
  { text: "Collective farming is generally superior to private farming.", axis: "ownership", direction: -1 },
  { text: "The ideal economy finds a balance between private initiative and collective good.", axis: "ownership", direction: 1 },
  { text: "Profits and wealth generated under the system should face minimal taxation.", axis: "ownership", direction: 1 },
  { text: "Land should not be treated as a freely tradable commodity.", axis: "ownership", direction: -1 },
  { text: "There should be only one national bank controlling finance.", axis: "ownership", direction: -1 },
  { text: "Workers should have ownership stakes or profit-sharing in the enterprises they work in.", axis: "ownership", direction: -1 },
  { text: "The businessperson and industrialist are more vital to society than artists or intellectuals.", axis: "ownership", direction: 1 },
  { text: "True economic independence is almost impossible without widespread private property.", axis: "ownership", direction: 1 },
  { text: "Distributism sounds good in theory but rarely works in practice.", axis: "ownership", direction: -1 },

  // ==================== TRADITION ====================
  { text: "Empire-building and territorial expansion can be noble and virtuous.", axis: "tradition", direction: -1 },
  { text: "War can impose nobility and discipline upon a people.", axis: "tradition", direction: -1 },
  { text: "Societies must adapt to foreign ideas and values to survive in the modern world.", axis: "tradition", direction: -1 },
  { text: "The monarchy is a vital cultural institution that must be preserved.", axis: "tradition", direction: 1 },
  { text: "We must revolt against modernity itself, not merely its current form.", axis: "tradition", direction: 1 },
  { text: "The distant past offered superior forms of social organization.", axis: "tradition", direction: 1 },
  { text: "Accelerationism is the best path forward.", axis: "tradition", direction: -1 },
  { text: "We should erase the remnants of past civilizations.", axis: "tradition", direction: -1 },
  { text: "Humanity should improve its biology through advanced technology.", axis: "tradition", direction: -1 },
  { text: "Environmental damage is acceptable if it serves national strength.", axis: "tradition", direction: -1 },
  { text: "The Industrial Revolution was a necessary and positive step in history.", axis: "tradition", direction: -1 },
  { text: "Traditional customs and societal norms strengthen communities.", axis: "tradition", direction: 1 },
  { text: "A better future will come primarily through science, automation and technology.", axis: "tradition", direction: -1 },
  { text: "We must protect nature even at the cost of material progress.", axis: "tradition", direction: 1 },
  { text: "Urban life is clearly superior to rural and agrarian living.", axis: "tradition", direction: -1 },
  { text: "We should approach new technologies with deep skepticism.", axis: "tradition", direction: 1 },
  { text: "Agriculture domesticated not only animals but human nature itself.", axis: "tradition", direction: 1 },
  { text: "Drug use and intoxication are immoral and should be socially condemned.", axis: "tradition", direction: 1 },
  { text: "A violent and heroic future must be embraced.", axis: "tradition", direction: -1 },
  { text: "The LGBTQ+ community should be allowed civil partnerships or equivalent recognition.", axis: "tradition", direction: -1 },
  { text: "It is the duty of government to enforce traditional morality.", axis: "tradition", direction: 1 },
  { text: "Individuals should have near-total freedom over their own bodies.", axis: "tradition", direction: -1 },
  { text: "Sexual deviancy and degeneracy should be tolerated.", axis: "tradition", direction: -1 },
  { text: "The fusion of information and entertainment is a worrying development.", axis: "tradition", direction: 1 },
  { text: "The most important thing for children is to learn discipline and duty.", axis: "tradition", direction: 1 },

  // ==================== FAITH ====================
  { text: "There are such things as inalienable natural rights.", axis: "faith", direction: 1 },
  { text: "All religions must be treated equally by the state.", axis: "faith", direction: -1 },
  { text: "Religious values should have no influence on governance.", axis: "faith", direction: -1 },
  { text: "Religion is essentially a psychic disease.", axis: "faith", direction: -1 },
  { text: "Religious morality mostly hinders human progress.", axis: "faith", direction: -1 },
  { text: "Strict separation of church and state is essential.", axis: "faith", direction: -1 },
  { text: "There exist moral absolutes that must never be violated.", axis: "faith", direction: 1 },
  { text: "Schools should provide spiritual or religious education.", axis: "faith", direction: 1 },
  { text: "Respect for our ancestors and ancestral traditions is important.", axis: "faith", direction: 1 },
  { text: "My own religion must be given proper respect and protection.", axis: "faith", direction: 1 },
  { text: "Atheism is generally deplorable and harmful to society.", axis: "faith", direction: 1 },
  { text: "True morality requires religious faith.", axis: "faith", direction: 1 },
  { text: "Paganism is primitive and barbaric.", axis: "faith", direction: -1 },
  { text: "I believe in the supernatural and transcendent realities.", axis: "faith", direction: 1 },
  { text: "Churches and religious institutions should pay taxes like everyone else.", axis: "faith", direction: 1 },
  { text: "I accept and respect other denominations within my faith.", axis: "faith", direction: -1 },
  { text: "Atheism leads to moral degeneracy.", axis: "faith", direction: 1 },
  { text: "Ethnicity and blood are spiritually connected to the land.", axis: "faith", direction: 1 },
  { text: "Idols and sacred objects of other faiths should be destroyed.", axis: "faith", direction: 1 },
  { text: "Satanism is simply another valid religion.", axis: "faith", direction: -1 },
  { text: "Traditional gender roles should be abolished.", axis: "faith", direction: -1 },
  { text: "Abortion is morally abhorrent and should be illegal.", axis: "faith", direction: 1 },
  { text: "It is best if political leaders are not personally religious.", axis: "faith", direction: -1 },
  { text: "Gnosticism is mostly conspiracy theories and imagination.", axis: "faith", direction: -1 },
  { text: "Astrology and similar practices can accurately explain reality.", axis: "faith", direction: -1 }
];
// Shuffle questions randomly every time the page loads
function shuffle(array) {
  let currentIndex = array.length;
  while (currentIndex !== 0) {
    let randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
  return array;
}

shuffle(questions);
